version = 0.1
[stage.deploy.parameters]
stack_name = "pipeline-stage"
resolve_s3 = true
s3_prefix = "pipeline-stage"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Env=\"stage\" BucketName=\"tradesecretsdata\" S3Prefix=\"scraper-dk\" RoleArn=\"arn:aws:iam::688035104276:role/lambda-stage\" ApiUrl=\"\""
image_repositories = []
