version = 0.1

# Shared build flags
[default.build.parameters]
use_container = false

# Stage
[stage.deploy.parameters]
stack_name = "pipeline-stage"
s3_bucket = "tradesecretsdata"
s3_prefix = "pipeline-stage"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Env=\"stage\" BucketName=\"tradesecretsdata\" S3Prefix=\"scraper-dk\" RoleArn=\"arn:aws:iam::688035104276:role/lambda-stage\" ApiUrl=\"\""
image_repositories = []

# Prod (CI/CD uses this)
resolve_s3 = true
[prod.deploy.parameters]
stack_name = "pipeline-prod"
s3_bucket = "tradesecretsdata"
s3_prefix = "scraper-dk/prod/sam-artifacts"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Env=\"prod\" BucketName=\"tradesecretsdata\" S3Prefix=\"scraper-dk\" RoleArn=\"arn:aws:iam::688035104276:role/lambda-prod\" ApiUrl=\"\""
image_repositories = []

